module miasma_atlas::evidence_capsule {
    public struct EvidenceCapsule has key, store {
        id: sui::object::UID,
        capsule_id: vector<u8>,
        capsule_hash: vector<u8>,
        action_kind: vector<u8>,
        intent_hash: vector<u8>,
        policy_hash: vector<u8>,
        context_hash: vector<u8>,
        memory_action_context_hash: vector<u8>,
        sui_digest: vector<u8>,
        deepbook_digest: vector<u8>,
        proof_hash: vector<u8>,
        public_signals_hash: vector<u8>,
        verification_state: vector<u8>,
        funds_moved: u64,
        blocked: bool,
        confirmation_required: bool,
        walrus_blob_id: vector<u8>,
        walrus_object_id: vector<u8>,
        walrus_status: vector<u8>,
        seal_policy_id: vector<u8>,
        seal_status: vector<u8>,
        seal_ciphertext_hash: vector<u8>,
        created_at_ms_or_epoch: u64,
    }

    public struct EvidenceCapsuleAnchored has copy, drop {
        capsule_id: vector<u8>,
        capsule_hash: vector<u8>,
        proof_hash: vector<u8>,
        public_signals_hash: vector<u8>,
        funds_moved: u64,
        blocked: bool,
        confirmation_required: bool,
    }

    public fun create_evidence_capsule(
        capsule_id: vector<u8>,
        capsule_hash: vector<u8>,
        action_kind: vector<u8>,
        intent_hash: vector<u8>,
        policy_hash: vector<u8>,
        context_hash: vector<u8>,
        memory_action_context_hash: vector<u8>,
        sui_digest: vector<u8>,
        deepbook_digest: vector<u8>,
        proof_hash: vector<u8>,
        public_signals_hash: vector<u8>,
        verification_state: vector<u8>,
        funds_moved: u64,
        blocked: bool,
        confirmation_required: bool,
        walrus_blob_id: vector<u8>,
        walrus_object_id: vector<u8>,
        walrus_status: vector<u8>,
        seal_policy_id: vector<u8>,
        seal_status: vector<u8>,
        seal_ciphertext_hash: vector<u8>,
        created_at_ms_or_epoch: u64,
        ctx: &mut sui::tx_context::TxContext,
    ) {
        let capsule = EvidenceCapsule {
            id: sui::object::new(ctx),
            capsule_id,
            capsule_hash,
            action_kind,
            intent_hash,
            policy_hash,
            context_hash,
            memory_action_context_hash,
            sui_digest,
            deepbook_digest,
            proof_hash,
            public_signals_hash,
            verification_state,
            funds_moved,
            blocked,
            confirmation_required,
            walrus_blob_id,
            walrus_object_id,
            walrus_status,
            seal_policy_id,
            seal_status,
            seal_ciphertext_hash,
            created_at_ms_or_epoch,
        };

        sui::event::emit(EvidenceCapsuleAnchored {
            capsule_id: capsule.capsule_id,
            capsule_hash: capsule.capsule_hash,
            proof_hash: capsule.proof_hash,
            public_signals_hash: capsule.public_signals_hash,
            funds_moved: capsule.funds_moved,
            blocked: capsule.blocked,
            confirmation_required: capsule.confirmation_required,
        });

        sui::transfer::public_share_object(capsule);
    }
}
